// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpacmloqsfiebvagfomt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYWNtbG9xc2ZpZWJ2YWdmb210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTI5NDYsImV4cCI6MjA4Nzc2ODk0Nn0.bRMeYGbG4m8B19rYof8t4G_U4NVoNZ95Q0QNQPXj5zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});